/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerticalRouteImport } from './routes/vertical'
import { Route as TaskDataTableRouteImport } from './routes/task-data-table'
import { Route as HorizontalRouteImport } from './routes/horizontal'
import { Route as IndexRouteImport } from './routes/index'

const VerticalRoute = VerticalRouteImport.update({
  id: '/vertical',
  path: '/vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskDataTableRoute = TaskDataTableRouteImport.update({
  id: '/task-data-table',
  path: '/task-data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizontalRoute = HorizontalRouteImport.update({
  id: '/horizontal',
  path: '/horizontal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horizontal': typeof HorizontalRoute
  '/task-data-table': typeof TaskDataTableRoute
  '/vertical': typeof VerticalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horizontal': typeof HorizontalRoute
  '/task-data-table': typeof TaskDataTableRoute
  '/vertical': typeof VerticalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horizontal': typeof HorizontalRoute
  '/task-data-table': typeof TaskDataTableRoute
  '/vertical': typeof VerticalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/horizontal' | '/task-data-table' | '/vertical'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/horizontal' | '/task-data-table' | '/vertical'
  id: '__root__' | '/' | '/horizontal' | '/task-data-table' | '/vertical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HorizontalRoute: typeof HorizontalRoute
  TaskDataTableRoute: typeof TaskDataTableRoute
  VerticalRoute: typeof VerticalRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/vertical': {
      id: '/vertical'
      path: '/vertical'
      fullPath: '/vertical'
      preLoaderRoute: typeof VerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-data-table': {
      id: '/task-data-table'
      path: '/task-data-table'
      fullPath: '/task-data-table'
      preLoaderRoute: typeof TaskDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horizontal': {
      id: '/horizontal'
      path: '/horizontal'
      fullPath: '/horizontal'
      preLoaderRoute: typeof HorizontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HorizontalRoute: HorizontalRoute,
  TaskDataTableRoute: TaskDataTableRoute,
  VerticalRoute: VerticalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
