/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestVerticalRouteImport } from './routes/test/vertical'
import { Route as TestTaskDataTableRouteImport } from './routes/test/task-data-table'
import { Route as TestResizableRouteImport } from './routes/test/resizable'
import { Route as TestHorizontalRouteImport } from './routes/test/horizontal'
import { Route as TestResizableCreateTaskRouteImport } from './routes/test/resizable/create-task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestVerticalRoute = TestVerticalRouteImport.update({
  id: '/test/vertical',
  path: '/test/vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTaskDataTableRoute = TestTaskDataTableRouteImport.update({
  id: '/test/task-data-table',
  path: '/test/task-data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResizableRoute = TestResizableRouteImport.update({
  id: '/test/resizable',
  path: '/test/resizable',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHorizontalRoute = TestHorizontalRouteImport.update({
  id: '/test/horizontal',
  path: '/test/horizontal',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResizableCreateTaskRoute = TestResizableCreateTaskRouteImport.update({
  id: '/create-task',
  path: '/create-task',
  getParentRoute: () => TestResizableRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/resizable': typeof TestResizableRouteWithChildren
  '/test/task-data-table': typeof TestTaskDataTableRoute
  '/test/vertical': typeof TestVerticalRoute
  '/test/resizable/create-task': typeof TestResizableCreateTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/resizable': typeof TestResizableRouteWithChildren
  '/test/task-data-table': typeof TestTaskDataTableRoute
  '/test/vertical': typeof TestVerticalRoute
  '/test/resizable/create-task': typeof TestResizableCreateTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/resizable': typeof TestResizableRouteWithChildren
  '/test/task-data-table': typeof TestTaskDataTableRoute
  '/test/vertical': typeof TestVerticalRoute
  '/test/resizable/create-task': typeof TestResizableCreateTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test/horizontal'
    | '/test/resizable'
    | '/test/task-data-table'
    | '/test/vertical'
    | '/test/resizable/create-task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test/horizontal'
    | '/test/resizable'
    | '/test/task-data-table'
    | '/test/vertical'
    | '/test/resizable/create-task'
  id:
    | '__root__'
    | '/'
    | '/test/horizontal'
    | '/test/resizable'
    | '/test/task-data-table'
    | '/test/vertical'
    | '/test/resizable/create-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestHorizontalRoute: typeof TestHorizontalRoute
  TestResizableRoute: typeof TestResizableRouteWithChildren
  TestTaskDataTableRoute: typeof TestTaskDataTableRoute
  TestVerticalRoute: typeof TestVerticalRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/vertical': {
      id: '/test/vertical'
      path: '/test/vertical'
      fullPath: '/test/vertical'
      preLoaderRoute: typeof TestVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/task-data-table': {
      id: '/test/task-data-table'
      path: '/test/task-data-table'
      fullPath: '/test/task-data-table'
      preLoaderRoute: typeof TestTaskDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/resizable': {
      id: '/test/resizable'
      path: '/test/resizable'
      fullPath: '/test/resizable'
      preLoaderRoute: typeof TestResizableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/horizontal': {
      id: '/test/horizontal'
      path: '/test/horizontal'
      fullPath: '/test/horizontal'
      preLoaderRoute: typeof TestHorizontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/resizable/create-task': {
      id: '/test/resizable/create-task'
      path: '/create-task'
      fullPath: '/test/resizable/create-task'
      preLoaderRoute: typeof TestResizableCreateTaskRouteImport
      parentRoute: typeof TestResizableRoute
    }
  }
}

interface TestResizableRouteChildren {
  TestResizableCreateTaskRoute: typeof TestResizableCreateTaskRoute
}

const TestResizableRouteChildren: TestResizableRouteChildren = {
  TestResizableCreateTaskRoute: TestResizableCreateTaskRoute,
}

const TestResizableRouteWithChildren = TestResizableRoute._addFileChildren(
  TestResizableRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestHorizontalRoute: TestHorizontalRoute,
  TestResizableRoute: TestResizableRouteWithChildren,
  TestTaskDataTableRoute: TestTaskDataTableRoute,
  TestVerticalRoute: TestVerticalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
